version: '3'
services:
  app:
    build: .
    container_name: statle-server
    environment:
      - DATABASE_URL=postgresql://root:wmXRAJB8ZH99obXIFjX0Msh6qGdHRuzG@dpg-ctqsim2j1k6c73aft4q0-a.oregon-postgres.render.com/champdb
      - JWT_SECRET=secret
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: wmXRAJB8ZH99obXIFjX0Msh6qGdHRuzG
      POSTGRES_DB: champdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: